### ISSUE TITLE
DICUI Doesn't Open

### ISSUE THREAD

**Issue by Melluish** [reignstumble/DICUI#104]
Double-clicking the application doesn't do anything. There were three entries in Event Viewer, 2 errors and 1 info (attached).
[error1.txt](https://github.com/reignstumble/DICUI/files/2219915/error1.txt)
[error2.txt](https://github.com/reignstumble/DICUI/files/2219916/error2.txt)
[info.txt](https://github.com/reignstumble/DICUI/files/2219917/info.txt)

**OS:**
Windows 10 Pro

**Drive:**
VendorId: TSSTcorp
ProductId: DVD-ROM SH-D163B
ProductRevisionLevel: SB01
VendorSpecific: KREON V1.00

I was able to successfully rip an OG Xbox disc by running the following from the "Programs" dir:
`DiscImageCreator.exe xbox e xboxgame.bin `

If you want any more info, please just ask.

**Comment by mnadareski** [comment]
What version are you running? Are you running the last official release? Or are you running an AppVeyor build?

**Comment by mnadareski** [comment]
Actually, scratch that, you're using 1.07. That has long since been fixed by wrapping those calls in a Try/Catch. Please try an AppVeyor build.

**Comment by Melluish** [comment]
Forgive me. How do I obtain the AppVeyor build? I downloaded it from the link you provide in the project's README: https://github.com/reignstumble/DICUI/releases

**Comment by mnadareski** [comment]
https://ci.appveyor.com/project/mnadareski/dicui/build/artifacts should do the trick. Just overwrite your existing setup with this.

**Comment by Melluish** [comment]
Thank you very much. I noticed the AppVeyor build doesn't contain the DiscImageCreator.exe or subdumo.exe, so it doesn't actually work. Is this right? I just pointed it to the executables bundled with the 1.07 build I downloaded previously and it's working okay. Any reason the working build isn't the latest available on GitHub?

**Comment by mnadareski** [comment]
Long story short is I need to figure out the best way of downloading and bundling the newest versions direct from GitHub. It might take a bit of fiddling. For now, the stuff in DICUI 1.07 would work fine, as would if you overwrote those with the newest DIC build available on GitHub.

**Comment by mnadareski** [comment]
Closing issue as base problem has been resolved. All other comments about AppVeyor should be put into a new issue if still a problem.
