### ISSUE TITLE
Print PS4 PIC.BIN info to !SubmissionInfo

### ISSUE THREAD

**Issue by dizzzy77** [reignstumble/DICUI#106]
I'm told the data can be gathered from a Hex Editor.

There's a PS4 pic.bin in here that can be used for testing: https://drive.google.com/open?id=1y6rGjEylg9yd92FNd4oEhx-IMwlK_ql5

**Comment by mnadareski** [comment]
Can you please detail what information has to be gathered from the PIC.bin? Possibly hex locations (or at least a link to documentation)?

**Comment by mnadareski** [comment]
Also unfortunately, the link provided does not contain a proper PIC.bin file. The one contained is 0 bytes.
