### ISSUE TITLE
Crashes when creating !Submissioninfo with CD-Rom that has Joliet

### ISSUE THREAD

**Issue by dizzzy77** [reignstumble/DICUI#107]
Tried two different CD-Roms with Joliet, both crashed at the final stage, dumping completed (including dat population etc).

**Comment by mnadareski** [comment]
From offline conversation, we have determined that there is some issue in the "detect if all files exist" code, but only for these types of discs, seemingly. That is why it seems that it's crashing. More testing will be needed to see what files it thinks are missing.

**Comment by mnadareski** [comment]
This ended up being related to the error checking issue previously fixed. Thanks to @dizzzy77 for verifying with the latest AppVeyor build.
