### ISSUE TITLE
Xbox 360 security ranges are not formatted for redump submission in !SubmissionInfo

### ISSUE THREAD

**Issue by dizzzy77** [reignstumble/DICUI#108]
Here's what ss_sector_range.exe outputs (and what redump.org accepts):
108976-113071
3719856-3723951

For the same ss.bin, here's what's in !submissioninfo (which redump rejects):
`Security Sector Ranges:

	          security sector ranges: 
		       Layer 0		Unknown:    31400, startLBA-endLBA:   108976-  113071
		Unknown ranges		Unknown:    18700, startLBA-endLBA:  2152432- 2156527
		Unknown ranges		Unknown:    3f300, startLBA-endLBA: 14648816-14652911
		       Layer 1		Unknown:    13e00, startLBA-endLBA:  3719856- 3723951
		Unknown ranges		Unknown:    7b600, startLBA-endLBA:   305584-  309039
		Unknown ranges		Unknown:    5d400, startLBA-endLBA:  2152432- 2155887
		Unknown ranges		Unknown:    71e00, startLBA-endLBA: 14648816-14652271
		Unknown ranges		Unknown:    54800, startLBA-endLBA: 16472944-16476399
		Unknown ranges		Unknown:     c900, startLBA-endLBA:  6720975-  680795
		Unknown ranges		Unknown:   e06a00, startLBA-endLBA:  6410317- 9269213
		Unknown ranges		Unknown:   f46000, startLBA-endLBA:  9512171-15690758
		Unknown ranges		Unknown:   fcb700, startLBA-endLBA:  8736385-16145778
		Unknown ranges		Unknown:   f6d300, startLBA-endLBA: 11062707-14218559
		Unknown ranges		Unknown:   f92500, startLBA-endLBA:  6850896- 2693006
		Unknown ranges		Unknown:   f0da00, startLBA-endLBA:  2453727- 3348870
		Unknown ranges		Unknown:   febf00, startLBA-endLBA:  2253923- 5719054
		Unknown ranges		Unknown:   f9cd00, startLBA-endLBA:  4872297- 2054867
		Unknown ranges		Unknown:   fa6400, startLBA-endLBA: 13429676- 4526356
		Unknown ranges		Unknown:   f93f00, startLBA-endLBA:  8150888- 5034591
		Unknown ranges		Unknown:   f35500, startLBA-endLBA:  6470212- 1498688
		Unknown ranges		Unknown:   f55200, startLBA-endLBA: 11254744- 5314243`

**Comment by mnadareski** [comment]
Fixed as of https://github.com/reignstumble/DICUI/commit/fff19e75fdfa35923122206edc63d6f53a66af3f
