### ISSUE TITLE
Have to close the app to dump the next disc

### ISSUE THREAD

**Issue by dizzzy77** [reignstumble/DICUI#110]
![capture](https://user-images.githubusercontent.com/39425903/43683312-aa0c29d8-983d-11e8-8e2f-2a5505c1485c.PNG)

Log window says completed, but main UI says "Stop Dumping"

This build was posted to the DICUI discord by Jack after 1.10, which kills off the terminal pop-up.

**Comment by mnadareski** [comment]
That's an unofficial build with the end-to-end logging in place. There is probably an issue on that end. In the meantime, there will be a fix to addess the possibility of it happening in the main branch.
