### ISSUE TITLE
Potential UX issue - a Speed is still shown on irrelevant commands

### ISSUE THREAD

**Issue by InternalLoss** [reignstumble/DICUI#113]
with the `xbox` command (and assumedly other commands such as Dreamcast HD, etc), speed is not passed to DIC, as it does not try to directly speed up a disc. However, a greyed-out speed selection is still shown, and is usually set to 8x. This may confuse a user, as they may feel that it is at 8x and is too slow, causing them anger. Even if 8x is the theoretical speed a drive runs at for Xbox discs, it still shouldnt be shown. Instead, an "N/A" or `-` would be better, where it implies that the Speed isn't set by DICUI.

**Comment by mnadareski** [comment]
This is basically fixed by https://github.com/reignstumble/DICUI/commit/75c18ea3c40f38146273db1bb71bb527e1a7f6ab since DIC now supports drive speed for both Blu-Ray and XBOX dumping methods
