### ISSUE TITLE
Saturn PVD data

### ISSUE THREAD

**Issue by dizzzy77** [reignstumble/DICUI#118]
http://redump.org/disc/55201/

Runs 0000 through 00F0, not the standard 0320.

**Comment by dizzzy77** [comment]
May have explained this incorrectly. Please see sega_systems channel on Discord from 9/10/2018 or DM Fireball when the time comes.

"I don't think that's the issue necessarily
if you look at this one:
http://redump.org/disc/16828/
It has a 'header' portion and also a 'pvd' portion
the 'header' portion pulls correctly in DIC
the pvd portion pulls 320 to 370, from the  LBA[000000, 0000000] Main channel, which is where the header part is

when it SHOULD be pulling fro LBA[000016, 0x00010]: Main Channel"

**Comment by mnadareski** [comment]
Please attach one of these new `_mainInfo.txt` files so I can see what the new differences are. I think the code currently assumes that all of these files start identically with the same sector.
