### ISSUE TITLE
Feature Request: Floppy Disk dumping

### ISSUE THREAD

**Issue by dizzzy77** [reignstumble/DICUI#12]
fd <DriveLetter> <Filename>
                Dumping a floppy disk

**Comment by mnadareski** [comment]
The issue with this as an option is that Floppy Disk drives show up as "Removable Drives" and not something unique like optical drives do. This causes the issue where we can't isolate the floppy drives accurately. That being said, when the custom parameter option is added, the fd command can be selected and then the user can customize the correct drive letter instead.

**Comment by mnadareski** [comment]
Currently "supported" via the custom parameters until the removable drive thing can be ironed out.
