### ISSUE TITLE
Mishandling Audio CD

### ISSUE THREAD

**Issue by elasticblitz** [reignstumble/DICUI#127]
Latest version of DICUI doesn't seem to handle Audio CD correctly:

- Doesn't detect the correct Media Type automatically for Audio CD (which isn't a very big issue, but getting that work would be nice);
- Cannot generate !submissioninfo.txt and outputs "dump may be incomplete", despite dumping is completed without errors.

Would you look into these issues? Thanks!

**Comment by mnadareski** [comment]
For point 1, not really much I can do about that due to how Windows detects media types.
Point 2 is a bit easier, and will be addressed soonish.

**Comment by BodyDub** [comment]
Can't dump audio-cd
https://i.imgur.com/O2eT0yJ.png

**Comment by mnadareski** [comment]
I'm not sure what you're trying to get at with the screenshot. It looks like you're just running DIC by itself (since DICUI sets the `/c2` value flag). Your drive doesn't appear to be fully supported by DIC. This project is ONLY for DICUI, not the underlying program of DIC.
