### ISSUE TITLE
3DO discs aren't regonized

### ISSUE THREAD

**Issue by dizzzy77** [reignstumble/DICUI#18]
It seems windows can't actually read these discs on a file/browser level, but DIC dumps them from the CLI process fine. DICUI doesn't do it :/

**Comment by dizzzy77** [comment]
note from emuload:
I noticed a wee bug with CD-i, since CD-i's FS is not recognized in windows, when scanning for discs DICUI would not find any, i think the issue is in the detection algo that checks (i guess) for windows to rec. the disc
if you load a PC CD, have it ID'd, set everything up, then change the disc in the drive and change the setting to CD-i DICUI will work, I suspect the same might be true here

**Comment by reignstumble** [comment]
I guess the only option I'll have is a "Add drive manually" option, because DICUI rely on Windows Disc detection to add the drive automatically...

**Comment by dizzzy77** [comment]
Hmmm maybe switching system to 3DO can trigger this. Same with Mac discs too :3

**Comment by reignstumble** [comment]
Yeah, might work, I'll have to figure out an elegant way.. :P

**Comment by reignstumble** [comment]
Found a way, it's on shedule for next release. :)
