### ISSUE TITLE
Extra \ when accepting default save location

### ISSUE THREAD

**Issue by avieros** [reignstumble/DICUI#19]
just tried in DICUI 1.02 - puts an additional slash if you leave the auto-filled directory setting.

cmd line (fails) C:\DICUI_1.02\Programs\DiscImageCreator.exe dvd M ISO\Kao_2\\Kao_2 8
settings here: https://imgur.com/a/MZ1h89K

clicking browse and selecting ISO dir manually works ok.
just the autofill seems to insert an additional \

**Comment by reignstumble** [comment]
Fixed, it's on shedule for next release. :)
