### ISSUE TITLE
edccchk should be run on all CD-Roms

### ISSUE THREAD

**Issue by dizzzy77** [reignstumble/DICUI#21]
This is currently implemented in PSX, but should be used for all CD-Rom formats :3

**Comment by reignstumble** [comment]
It's on shedule for next release. :)

**Comment by mnadareski** [comment]
Doesn't DIC automatically run this? I've always seen the .IMG file get an _eccEdc.txt file created...

**Comment by mnadareski** [comment]
Pinging this again, since I think that this was an unnecessary addition.
