### ISSUE TITLE
Feature Request: Centralized Disc Info

### ISSUE THREAD

**Issue by mnadareski** [reignstumble/DICUI#23]
For submitting discs, a lot of information needs to be consolidated from across multiple output files. It would be good if all of these could be automatically rounded up and made into a templated file that would be appropriate for the type of disc being dumped.

Of note, if any dump whatsovever has the _mainError.txt file with a size > 0, then the dump is not good. This is where hardware issues and errors get stored, so the output file should never be considered correct.

**Comment by reignstumble** [comment]
This should be implemented on v1.04

**Comment by mnadareski** [comment]
In the codebase as of the latest version.
