### ISSUE TITLE
Detect Disc Type Button

### ISSUE THREAD

**Issue by dizzzy77** [reignstumble/DICUI#49]
![detect](https://user-images.githubusercontent.com/39425903/41493372-58c69de6-70bb-11e8-8329-9d51588eea99.png)

A button to Detect the disc type based on format and root files / structure.

Certain formats follow certain rules / have root files or folders making them easy to detect with one-click, as opposed to finding the format manually.

**Comment by mnadareski** [comment]
Can you give some examples? The only ones I'm aware of are the PS1/PS2 ones (and even then, hard to tell apart).

**Comment by dizzzy77** [comment]
Work in progress guide:

Sony:
- PS1: has the serial number (generally, except for some unlicensed, but this doesn't have to be fullproof), has no system.cnf
- PS2 CD-Rom: is CD-Rom format, has a system.cnf
- PS2 DVD-Rom: is DVD-Rom format, has a system.cnf
- PS4: has PSLogo.ico in root, bd format

Microsoft - not sure about these
-Xbox: 
-Xbox 360: 
-Xbox One: 

Sega:
-Saturn:  not sure
-Mega CD: not sure
-Dreamcast: is a GD-Rom

Vtech Vsmile Pro
-Has a "0SYSTEM" folder in the root

Misc: 
- Audio CD: all Audio tracks

----

As a general note, this feature doesn't have to be able to detect ALL disc types to be helpful. Even a handful or half the systems would be useful, especially for mass dumping.

**Comment by dizzzy77** [comment]
Maybe this feature is just overkill, but as the list of systems grow on redump, i figured it might be worth a shot? Probably best if we could get all the popular systems working - if that's even possible.

**Comment by mnadareski** [comment]
Only issue would be something like determining if something is CD or DVD just from the media. Like a PS2 CD vs PS2 DVD. Well, not the only issue, but one of them.

**Comment by gingerbeardman** [comment]
Is this in the release version?

I'm using 1.12.2 and I do not see the detect button nor do my PS1 games get automatically detected?

**Comment by gingerbeardman** [comment]
Having checked the commits, it seems that the code now sets disc type (part of this proposal) but not system (the other half of this proposal) which would be really useful. I'll open a new issue.
