### ISSUE TITLE
Read speed fails to read and crashes DICUI if another instance is running

### ISSUE THREAD

**Issue by Jakz** [reignstumble/DICUI#55]
System.AgumentOutOfRangeException is raised in `MainWindow.xaml.cs`, inside `SetSupportedDriveSpeed()` function, here:

    string readspeed = Regex.Match(output.Substring(index), @"ReadSpeedMaximum: [0-9]+KB/sec \(([0-9]*)x\)").Groups[1].Value;

when output from DIC fails to produce expected output (for instance if another instance is already dumping).

**Comment by mnadareski** [comment]
Extra info: Probably related to the `Groups[1]` part of the code more than anything. Will investigate.

**Comment by mnadareski** [comment]
No longer crashes, but now freezes both the running instance of DIC and DICUI
