### ISSUE TITLE
DiscImageCreator doesn't have a speed option when dumping Blu-Rays, DICUI thinks it does.

### ISSUE THREAD

**Issue by ajshell1** [reignstumble/DICUI#7]
Here's a nice and simple issue. I tried to dump an Xbox One disc recently with DICUI at dizzzy77's request, even though I had already dumped a disc and got a matching checksum with ImgBurn. However, I was getting the error "Unknown option: [6]", which would later be "Unknown option: [4]" and then ""Unknown option: [8]" after messing with the disc speed. It turns out that DiscImageCreator doesn't have an option for dumping Blu-Rays at a specific speed, and that DICUI is adding it in anyway. As a result, selecting "Xbox One" or "PS4" in DICUI won't produce a proper dump.

**Comment by reignstumble** [comment]
Will fix that asap, thanks for the info!

**Comment by reignstumble** [comment]
Fixed in 1.02
