### ISSUE TITLE
Report if an X360 disc has XGD3

### ISSUE THREAD

**Issue by dizzzy77** [reignstumble/DICUI#71]
A popup message like this could come up:

This disc uses XGD3 copy protection, and will require an alternate dumping method. [See this guide.](http://wiki.redump.org/index.php?title=Microsoft_Xbox_360_Dumping_Guide)

**Comment by dizzzy77** [comment]
The idea being to make it simple on users, instead of just failing the dump.

**Comment by InternalLoss** [comment]
The error seems to be similar each time, and would be somewhat detectable. XGD3 also doesn't seem to work with 0800 drives using DICUI, afaik.

**Comment by mnadareski** [comment]
XDG3 isn't supported via DIC, so it's not supported via DICUI, regardless of drive used.

**Comment by mnadareski** [comment]
This is no longer an issue due to DIC's support of XGD3 discs on Kreon now.

**Comment by InternalLoss** [comment]
💖
