### ISSUE TITLE
Windows 7 SP1 - Crashes on CD Dump

### ISSUE THREAD

**Issue by InternalLoss** [reignstumble/DICUI#72]
**Short description**: DICUI will crash on "Start Dumping" with IBM CD set, using an IDE drive externally attached.

**Steps to Reproduce**:
1. Connect a drive (I'm using a Plextor 716A over a UGREEN IDE/m-IDE/SATA adapter with the 12V AC adapter plugged in for more power) to a computer over USB (I'm using USB 2.0)
2. Launch DICUI.
3. Select IBM Compatible CD-Rom, and your settings
4. Press Start Dumping, and it crashes with [the following error log](https://ghostbin.com/paste/hk4rc)

**System Information**: ThinkPad T61, Windows 7 Ultimate SP1, Intel Core 2 Duo T7100 1.8GHz, 4GB RAM. System is not yet activated, and at the time of the bug had 0 updates installed from Windows Update, but had .NET 4 and VCRedist installed using Microsoft's own installers.

**Comment by reignstumble** [comment]
Non-issue. Peoples should always have all Windows Updates installed, it's common sense imo.
