### ISSUE TITLE
Report if Plextor doesn't have final firmware

### ISSUE THREAD

**Issue by dizzzy77** [reignstumble/DICUI#81]
DICUI fails to launch if the Plextor drive doesn't have the final firmware. When running in DIC CLI it reports back to the user that the firmware isn't up to date.

Here's a message that could pop up:
"Please update your Plextor firmware to the final revision. You can download the final firmware for your Plextor model [here](http://wiki.redump.org/index.php?title=DiscImageCreator:_Optical_Disc_Drive_Compatibility#CD-Rom_.2F_CD-Audio)."

**Comment by mnadareski** [comment]
What exactly does DIC show when your firmware is out of date? Is it something that is the same each time? Either copy-paste it here or take a screenshot, if possible.

**Comment by dizzzy77** [comment]
Here's from Diego's message on Discord:

`C:\Users\diego\Desktop\DICUI\Programs>DiscImageCreator.exe cd e SCES-01737.bin 8 /c2 /nl
AppVersion
        x86, AnsiBuild, 2018/06/14 18:37:28
/c2 val1 is omitted. set [4000]
/c2 val2 is omitted. set [0]
CurrentDirectory
        C:\Users\diego\Desktop\DICUI\Programs
WorkingPath
         Argument: SCES-01737.bin
         FullPath: C:\Users\diego\Desktop\DICUI\Programs\SCES-01737
            Drive: C:
        Directory: \Users\diego\Desktop\DICUI\Programs\
         Filename: SCES-01737
        Extension: .bin
StartTime: 2018/06/22(Fri) 18:24:56
[ERROR] This drive isn't latest firmware. Please update.
EndTime: 2018/06/22(Fri) 18:24:56`
