### ISSUE TITLE
Copy Protection Additions

### ISSUE THREAD

**Issue by mnadareski** [reignstumble/DICUI#83]
This is a dumping ground for all known copy protections that are not detected by DICUI properly. For anyone commenting, please include the name of the disc, the name of the file, the protection that DICUI detected and the protection that ProtectionId detected. This will help keep track of things for better testing.

Known issues:
- No sector scanning
- Minor scanning of textfiles
- No scanning of archives - 7Z, RAR, PKZIP, ARC
- No internal key decryption for DVD, HD-DVD, BD, UHD-BD
    - DVD CSS keys taken care of by `CSS.exe` for DiscImageCreator (test build)
    - HD-DVD unhandled
    - BD/UHD-BD unhandled
- The following protection schemes need to be verified in the real world due to a decrement operation used in the code:
    - SolidShield 2, SolidShield 2 + TAGES
    - TAGES
    - VOB ProtectCD/DVD

| Disc Name | File Name | DICUI | PiD | Reported By |
| ------------ | ----------- | ------ | ---- | -------------  |
| Wiggles (DE) | N/A | N/A | N/A (VOB Protect CD/DVD should be) | Kludge |

**Comment by dizzzy77** [comment]
BD-Video / UHD BD-Video keys DB https://forum.doom9.org/showthread.php?t=175194

**Comment by mnadareski** [comment]
This has been migrated to the BurnOutSharp issue tracker: [Copy Protection Additions](https://github.com/mnadareski/BurnOutSharp/issues/1)
