### ISSUE TITLE
Feature Request: Redump info submission summary in single text file.

### ISSUE THREAD

**Issue by dizzzy77** [reignstumble/DICUI#9]
Output a new text file with pertinent information pertaining to the specific console for easy redump.org submission.

**Comment by dizzzy77** [comment]
Output map here: https://docs.google.com/document/d/1aybwa-Be1udD0DBaSdA-Xc0ddbcEGq_HgAfqEolX4Lw/edit

**Comment by mnadareski** [comment]
In the codebase as of the latest version.
