### ISSUE TITLE
Failed to dump PS2 CD-ROM

### ISSUE THREAD

**Issue by SvenDaHacker64** [reignstumble/DICUI#99]
I am trying to dump the Crash Bandicoot Wrath of Cortex disc and it doesn't properly dump, it throws error instead. I can dump the PS2 DVD fine.

The optical drive I'm using is LG Slim Portable DVD Writer GP57EB40.

My setup
![2018-07-16_15-46-59_dicui](https://user-images.githubusercontent.com/29345291/42765274-8bd2c220-890f-11e8-9474-0a2877b6119f.png)

Here's what it printed when I hit Start Dumping:
```
AppVersion
        x86, AnsiBuild, 20180619 20619
/c2 val2 is omitted. set [0]
E:\Dumped games\PS2\DICUI_1.07\ISO\CRASH\ doesn't exist, so create.
CurrentDirectory
        E:\Dumped games\PS2\DICUI_1.07
WorkingPath
         Argument: ISO\CRASH\CRASH.bin
         FullPath: E:\Dumped games\PS2\DICUI_1.07\ISO\CRASH\CRASH
            Drive: E:
        Directory: \Dumped games\PS2\DICUI_1.07\ISO\CRASH\
         Filename: CRASH
        Extension: .bin
StartTime: 2018/07/16(Mon) 16:07:18
Set the drive speed: 1411KB/sec
This drive can read a data sector at scrambled mode [OpCode: 0xbe, C2flag: 1, SubCode: 0]
This drive can read a data sector at scrambled mode [OpCode: 0xbe, C2flag: 1, SubCode: 1]
This drive can read a data sector at scrambled mode [OpCode: 0xbe, C2flag: 1, SubCode: 2]
This drive can read a data sector at scrambled mode [OpCode: 0xbe, C2flag: 1, SubCode: 4]
LBA[-00001, 0xffffffff]: [F:ReadCDForCheckingReadInOut][L:475]
        Opcode: 0xbe
        ScsiStatus: 0x02 = CHECK_CONDITION
        SenseData Key-Asc-Ascq: 05-2c-00 = ILLEGAL_REQUEST - COMMAND SEQUENCE ERROR
lpCmd: be, 04, ff, ff, ff, ff, 00, 00, 01, f8, 00, 00
dwBufSize: 2352
This drive can't read the lead-in
EndTime: 2018/07/16(Mon) 16:07:19
```

**Comment by mnadareski** [comment]
What the output is telling you is that DiscImageCreator can't read the lead-in for your drive, which means that it is not supported for CD dumping. Please see https://github.com/saramibreak/DiscImageCreator for more details.

**Comment by SvenDaHacker64** [comment]
Ah, that's why I can't dump... I'm gonna try a different DVD drive on other PC.

**Comment by mnadareski** [comment]
You might want to check the list of supported drives on DIC's GitHub page linked above. CD support in DIC is fiddly due to some requirements that newer drives can't fulfill.

**Comment by mnadareski** [comment]
Closing due to it not being a DICUI issue.
